### ISSUE TITLE
trigger doesn't work 

### ISSUE THREAD

**Issue by mosespx** [krpn/prometheus-alert-webhooker#16]
I'm getting the following error when it triggering a job, and it doesn't trigger the jenkins-job: 

> {"alert":"ALERT","context":"runner","details":{"job":"ilai-run-gor-staging-1"},"duration":"712.840438ms","event_id":"899d","executor":"Jenkins","level":"error","msg":"runner got executing task #1/1 error, stopping group: Could not invoke job ","result":"exec_error_without_block","rule":"JenkinsAutofix","tasks":[{"alert":"ALERT","details":{"job":"ilai-run-gor-staging-1"},"event_id":"899d","executor":"Jenkins","rule":"JenkinsAutofix"}],"time":"2019-04-17T15:55:01Z"}
> {"context":"runner","level":"debug","msg":"runner finished executing group","tasks":[{"alert":"ALERT","details":{"job":"ilai-run-gor-staging-1"},"event_id":"899d","executor":"Jenkins","rule":"JenkinsAutofix"}],"time":"2019-04-17T15:55:01Z"}

**Comment by krpn** [comment]
Hello, @mosespx

Please show me your config (do not forget to hide password).

**Comment by mosespx** [comment]
Hi @krpn this is the config file:

```
# cache size for blocked tasks
# 50 * 1024 * 1024 = 50 MB
block_cache_size: 52428800

# pool size for new tasks
# locks webhook if overflow
pool_size: 100

# runners count for parallel actions execute
runners: 10

# remote config refresh interval
# rules refreshed only
remote_config_refresh_interval: 60s

# common parameters for actions
common_parameters:
  jenkins_credentials:
    endpoint: https://jenkins-url.corp.com/
    login: prometheus
    password: <PASSWORD>
    state_refresh_delay: 5s


# list of rules to check and act
rules:
- name: JenkinsAutofix
  conditions:
    labels:
      #webhooker_jenkins_autofix: enabled # auto fix enabled
      #jenkins_job: (.*?)                 # jenkins job is set
      intent: jenkins-webhook
  actions:
  - executor: jenkins
    common_parameters: jenkins_credentials
    parameters:
      #job: ${ANNOTATION_JENKINS_JOB} # job name from annotation jenkins_job
      job: ilai-run-gor-staging-1 # job name from annotation jenkins_job
#    block: 10m
```
