### ISSUE TITLE
how to add multiple parameters in jenkins job ?

### ISSUE THREAD

**Issue by SuryaBalasubramaniyan** [krpn/prometheus-alert-webhooker#18]
- name: LowDiskSpaceLogsFix
  conditions:
    alert_labels:
      alertname: LowDiskSpace
      instance: ^logs_(.*?)
  actions:
  - executor: jenkins
    common_parameters: jenkins_credentials
    parameters:
      job: ${ANNOTATION_JENKINS_JOB} # job name from annotation jenkins_job
      job parameters: <how to add multiple values?>
    block: 10m

**Comment by krpn** [comment]
@SuryaBalasubramaniyan,
```yaml
...
  - executor: jenkins
    parameters:
       parameter1: value1
       parameter2: value2
...
```
