### ISSUE TITLE
Unable to run the test job

### ISSUE THREAD

**Issue by pratikshaprab** [krpn/prometheus-alert-webhooker#31]
We followed all the instructions yet the test job was not triggered. We are getting 200 response from Webhook app but it didn't trigger jenkins job

**Comment by krpn** [comment]
@pratikshaprab, show me your config please.

**Comment by venkateshmadala** [comment]
@krpn 
Below is config.yaml file we used.

```
block_cache_size: 52428800
pool_size: 100
runners: 10
remote_config_refresh_interval: 60s
common_parameters:
  jenkins_credentials:
    endpoint: http://localhost:8080/
    login: <username>
    password: <password>
    state_refresh_delay: 5s

rules:
- name: JenkinsAutofix
  conditions:
    alert_labels:
      alertname: HostOutOfDiskSpacedevice
      group: testapp
  actions:
  - executor: jenkins
    common_parameters: jenkins_credentials
    parameters:
      job: testjob
    block: 1m
```
    
To test the job we ran below curl command as per documentation.
`curl -i -X POST http://localhost:8081/webhooker -d '{
      "version": "1",
      "status": "firing",
      "truncatedAlerts": 0,
      "alerts": [
        {
          "labels": {
              "alertname": "HostOutOfDiskSpacedevice",
              "group": "testapp"
          }
        }
      ]
    }'`
    
We can see below message in webhook logs.

`{"alert":"HostOutOfDiskSpacedevice","context":"runner","details":{"job":"testjob"},"duration":"432.001383ms","event_id":"e5c6","executor":"Jenkins","level":"error","msg":"**runner got executing task #1/1 error, stopping group: Could not invoke job testjob**","result":"exec_error","rule":"JenkinsAutofix","tasks":[{"alert":"HostOutOfDiskSpacedevice","details":{"job":"testjob"},"event_id":"e5c6","executor":"Jenkins","rule":"JenkinsAutofix"}],"time":"2022-05-16T12:05:15Z"}
`
